name: CI/CD to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19' # Use the Go version you're using

    - name: Install dependencies
      run: cd ./Flash_queue_backend && go mod tidy
      
    - name: golangci-lint
      run: http://github.com/golangci/golangci-lint/cmd/golangci-lint@v1.60.3
      
    - name: Run tests
      run: cd ./Flash_queue_backend && go test ./...

    - name: Build project
      run:  cd ./Flash_queue_backend && go build -o Flash Queue

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST "https://api.render.com/v1/services/your-service-id/deploys" \
        -H "Authorization: Bearer $RENDER_API_KEY"
